### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by nashosted** [SelfhostedPro/selfhosted_templates#15]
How can we manage services that will require a database?

**Comment by SelfhostedPro** [comment]
Here is how I did it for bookstack:

In the templates.json you'll set it's block up like this:
```
  {
    "type": 2,
    "title": "bookstack",
    "name": "bookstack",
    "description": "Bookstack is a free and open source Wiki designed for creating beautiful documentation. Feautring a simple, but powerful WYSIWYG editor it allows for teams to create detailed and useful documentation with ease.",
    "logo": "https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/bookstack2.png",
    "categories": [
      "Wiki"
    ],
    "platform": "linux",
    "repository": {
      "url": "https://github.com/SelfhostedPro/selfhosted_templates",
      "stackfile": "Template/Stack/bookstack.yml"
    },
    "env": [
      {
        "name": "PUID",
        "label": "PUID",
        "default": "1000",
        "preset": true
      },
      {
        "name": "PGID",
        "label": "PGID",
        "default": "100",
        "preset": true
      },
      {
        "name": "Database_Password",
        "label": "Database Password"
      },
      {
        "name": "MYSQL_ROOT_PASSWORD",
        "label": "MYSQL_ROOT_PASSWORD"
      }
```
You'll then need to create a new $servicename.yml file in the Stack directory like this:
```
---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${DATABASE_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /portainer/Files/AppData/Bookstack/Data:/config
    ports:
      - ${PORT}:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${Timezone}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /portainer/Files/AppData/Bookstack/DB:/config
    restart: unless-stopped
```

Environment variables in the template.json correspond to variables in the stack template ( ${VARIABLE} will be replaced with whatever is input for the VARIABLE env variable in the template.json)
